% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Sep-2021 01:34:38
%  MATLAB version: 9.10.0.1710957 (R2021a) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('Final_MATLAB_litecoin_predict.mat');

A = saveVarsMat.A; % <2991x1 double> too many elements

AA = saveVarsMat.AA; % <1709x1 double> too many elements

B = saveVarsMat.B; % <2991x1 double> too many elements

BB = saveVarsMat.BB; % <1709x1 double> too many elements

C = saveVarsMat.C; % <2991x2 double> too many elements

DateRange = saveVarsMat.DateRange; % <1x1 datetime> unsupported class

EndDate = saveVarsMat.EndDate; % <1x1 datetime> unsupported class

IDdata = saveVarsMat.IDdata; % <1x1 iddata> unsupported class

LowerBound = saveVarsMat.LowerBound; % <1x1 iddata> unsupported class

StartDate = saveVarsMat.StartDate; % <1x1 datetime> unsupported class

UpperBound1 = saveVarsMat.UpperBound1; % <1x1 iddata> unsupported class

modelOrder = 5;

numSamples = 2991;

opt = saveVarsMat.opt; % <1x1 idoptions.ar> unsupported class

sampleTime = 1;

sys = saveVarsMat.sys; % <1x1 idpoly> unsupported class

sysf = saveVarsMat.sysf; % <1x1 idss> unsupported class

trend = saveVarsMat.trend; % <1x1 idpack.TrendInfo> unsupported class

x = saveVarsMat.x; % <2991x5 double> too many elements

x0 = [51.323017056140074; 50.410626656140082; 57.24323025614008; 26.308534528070034; ...
      12.320269239035017];

x_sd = saveVarsMat.x_sd; % <2991x5 double> too many elements

yf = saveVarsMat.yf; % <1x1 iddata> unsupported class

yf_sd = saveVarsMat.yf_sd; % <2991x1 double> too many elements

clear saveVarsMat;
